### ISSUE TITLE
[Bug] project has about us page, link to footer about page

### ISSUE THREAD

**Issue by nilesh-fatfatwale** [Yashgabani845/hiring-portal#10]
there is no link set on about us in the footer

**Comment by Yashgabani845** [comment]
go ahead set these links :
instra: https://www.instagram.com/yash845_/
github : https://github.com/Yashgabani845
linkedin : https://www.linkedin.com/in/yash-gabani-527886258/
facebook : same as instragram 
twitter: https://x.com/Hirehub280355

**Comment by ArthKulkarni93** [comment]
If no-one is assigned to this, can I do this in 1 day at max?
