### ISSUE TITLE
[Feature] Build a Blog page

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Yashgabani845/hiring-portal#104]
we can build a blog page where people can share there experience that how was there interview how they crack it how they prepare and all the other details

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah start working on it

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah do it carefully  make model of blog ans implement full feature and put section in homepage

**Comment by geetanjalidubey9** [comment]
pls assign this task to me

**Comment by Sawan-Kushwah** [comment]
@geetanjalidubey9 I am working on it try to find soem unsigned issue
