### ISSUE TITLE
Improving the 404 page

### ISSUE THREAD

**Issue by G-Rajashekar** [Yashgabani845/hiring-portal#107]
Current 404 page is not that good looking.I can design a better 404 page.
<img width="463" alt="image" src="https://github.com/user-attachments/assets/1319f34c-4e4e-4c07-b25b-4f0b589c631f">

**Comment by G-Rajashekar** [comment]
can you assign this issue to me with labels gssoc-ext

**Comment by Yashgabani845** [comment]
@G-Rajashekar it is not from our side it is from netlify 
well you can create custome 404 page and add it's route in home page check local code
