### ISSUE TITLE
cant post job

### ISSUE THREAD

**Issue by Garvit1000** [Yashgabani845/hiring-portal#114]
**Describe the bug**
 we cant post job  because of api error
![Screenshot from 2024-10-10 15-49-50](https://github.com/user-attachments/assets/5ae0605f-d176-4509-8812-5ffba8cc54a6)

**To Reproduce**
1. Go to 'employer dashboard '
2. Click on 'post job'
3. See error

**Expected behavior**
 job should be posted  without any error

@Yashgabani845  assign me this  i will  make combine PR of  filter and this  issue

**Comment by Yashgabani845** [comment]
@Garvit1000go ahead

**Comment by Garvit1000** [comment]
done 
![Screenshot from 2024-10-10 21-56-02](https://github.com/user-attachments/assets/bdc7f3d9-8e39-4862-9271-7b146dee350e)
issue  resolved  should i go for  PR @Yashgabani845

**Comment by Garvit1000** [comment]
posted PR
