### ISSUE TITLE
[Feature] Enhance the Login/SignUp functionality using OAuth2.0

### ISSUE THREAD

**Issue by ByteBard18** [Yashgabani845/hiring-portal#117]
Feature Update!
Currently, the user can only Login using email/password. A Web Application providing Hiring Solutions must have an option of Signing in using Google Accounts.

Proposed Solution:
Using OAuth2.0 and Google API to add an extra feature for SignIn and Signup can create a better User Experience and Seamless Account Management. 

Some Additional Things to note:
Also, the sign up link seems broken, I would like to fix that as well as include new features. Using Clerk can also be a work around for a better Profile Management and User Authentications.

Would really love to contribute these features to your web-app if you wish to assign me this issue!

**Comment by Yashgabani845** [comment]
@ByteBard18 go ahead

**Comment by Yashgabani845** [comment]
@ByteBard18 any updates or i should close  this issue
it's not that big issue

**Comment by haseebzaki-07** [comment]
hey @Yashgabani845 can I take this issue??
