### ISSUE TITLE
[Bug] HireHub Button Bug

### ISSUE THREAD

**Issue by Abhishek2634** [Yashgabani845/hiring-portal#12]
**Describe the bug**
when click on hirehub nothing happens . i want to redirect it to home page when we click hirehub.

**Screenshots**
<img width="205" alt="Screenshot 2024-10-02 at 2 43 47 PM" src="https://github.com/user-attachments/assets/e6063a3d-fd3c-4c27-85e5-5275d6f0e73c">

**Comment by Yashgabani845** [comment]
go ahead it is too small issues you will get only gssoc-extd label for this
