### ISSUE TITLE
[Feature] Add: "auto-label" GitHub Workflow for Automated Labeling

### ISSUE THREAD

**Issue by samyak-aditya** [Yashgabani845/hiring-portal#122]
**Objective:** Implement an "auto-label" GitHub workflow to automatically assign the "gssoc-ext" and "hacktoberfest-accepted" labels to relevant pull requests and issues.

**Details:**

- This workflow will streamline the labeling process by automatically applying the "gssoc-ext" and the "hacktoberfest-accepted" label to Issues.
- By automating these labels, we can ensure consistent tracking and visibility of contributions tied to these significant events.

Implementing this "auto-label" workflow will enhance project organization 

hey @Yashgabani845  Please Assign it to me with label "gssoc-ext" , "hacktoberfest-accepted" and "level2"

**Comment by Yashgabani845** [comment]
@samyak-aditya work on it and give label of hactoberfest,hactoberfest-accepted, gssoc-ext as default

**Comment by samyak-aditya** [comment]
hey @Yashgabani845 I would highly appreciate if you label it level2

**Comment by samyak-aditya** [comment]
Hey @Yashgabani845 I have created the PR
