### ISSUE TITLE
[Bug] Job section not responsive in mobile phone 

### ISSUE THREAD

**Issue by Abhishek2634** [Yashgabani845/hiring-portal#13]
**Describe the bug**
job section is not responsive. i will make it responsive in mobile

**To Reproduce**
1. Go to  job page
3. inspect and set dimension for mobile phone

**Expected behavior**
it should be visible good in phone

**Screenshots**
<img width="343" alt="Screenshot 2024-10-02 at 2 43 25 PM" src="https://github.com/user-attachments/assets/68dabbfa-ee18-4065-8dbf-1dce3755eaf0">

**Comment by Abhishek2634** [comment]
@Yashgabani845  assign this issue to me.

**Comment by Yashgabani845** [comment]
go ahead , good issue work on it and make sure you share video after making it responsive at both view laptop,mobile while making PR

**Comment by Abhishek2634** [comment]
you assigned to other bro

**Comment by Yashgabani845** [comment]
@Abhishek2634  sorry for inconvience , happy contributing !

**Comment by Yashgabani845** [comment]
@Abhishek2634 what is the update??

**Comment by sameer-soni** [comment]
@Yashgabani845 can I get assigned to this issue?

**Comment by Yashgabani845** [comment]
@sameer-soni start working on it 
there is no respone from @Abhishek2634

**Comment by sameer-soni** [comment]
@Yashgabani845 okay, can you add 'level' label?

**Comment by sameer-soni** [comment]
@Yashgabani845 there shouldn't be space in 'level 2' label for the issue to get count in gssoc, can you please fix it.

**Comment by sameer-soni** [comment]
@Yashgabani845 i have solved this issue, please fix the label spacing issue in 'level 2' then you can merge.

**Comment by Yashgabani845** [comment]
@sameer-soni don't worry it's allowed
