### ISSUE TITLE
Wrong Hacktoberfest Labels - GSSOC Extended ⚠️ 

### ISSUE THREAD

**Issue by MastanSayyad** [Yashgabani845/hiring-portal#130]
Hi @Yashgabani845 

I noticed you have spelling mistakes in your hacktoberfest labels
kindly edit and fix it

Correct labels: `hacktoberfest` `hacktoberfest-accepted`

Thank you!

**Comment by Yashgabani845** [comment]
@MastanSayyad I will change it asap

**Comment by Yashgabani845** [comment]
@MastanSayyad done
