### ISSUE TITLE
improve the user profile page

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#133]
the user profile page is not looking good 

![image](https://github.com/user-attachments/assets/de36c2f7-cf3b-4cf1-b413-adc0181d8bdc)

instead of having seperate divs for education, past jobs and skills  i want to add different tabs on single page 
which will enhance the ui design and user experience

i will use antd for this purpose 

please assign this issue to me @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72  it has been improved please prefer local version rather than deployed 
because of lot's of contributors are here so it is acing issue in builf so i have  not updated till now i will update it after program
