### ISSUE TITLE
[Bug] Login page not responsive.

### ISSUE THREAD

**Issue by Abhishek2634** [Yashgabani845/hiring-portal#14]
**Describe the bug**
Login page is not responsive in mobile

**Screenshots**
<img width="323" alt="Screenshot 2024-10-02 at 2 41 00 PM" src="https://github.com/user-attachments/assets/d4152ba1-1579-407a-97fa-1e32d5ffa3a9">

**Comment by Abhishek2634** [comment]
@Yashgabani845  assign this to me

**Comment by ShivaniNikam1** [comment]
@Yashgabani845 Heyyy can you please assign this issue to me, so that I can start working on it!

**Comment by Yashgabani845** [comment]
@ShivaniNikam1 start working on it

**Comment by slavomirStucka** [comment]
Hii i wanna work on it. Can you please assign this issue to me ? i can start right now!
