### ISSUE TITLE
[Feature] Adding a subscribe to our newletter option in footer and send mail to user about subscribed newletter.

### ISSUE THREAD

**Issue by VinayLodhi1712** [Yashgabani845/hiring-portal#141]
**Is your feature request related to a problem? Please describe.**
Adding a subscribe to our newletter option in footer and send mail to user when he put his mail in box and click on subscribe then mail goes to his mail id and there should be written that subscribed successfully and then home page link with explore more option.

**Describe the solution you'd like**
 frontend can be done easily and in backend i am going to use nodemailer and then sending mail with creating an api and fetch on frontend.

User get the mail successfully.

**Comment by Yashgabani845** [comment]
@VinayLodhi1712 work on it

**Comment by VinayLodhi1712** [comment]
ok also add level in it.
