### ISSUE TITLE
add skeleton palceholder

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#144]
when the profile is loaded or refreshed only a text loading profie..... is shown 
instead i will add skeleton loading for the different parts of the profile page 

![image](https://github.com/user-attachments/assets/c65f452b-5a60-44de-8443-7d5b544a180b)

please assign this issue to me @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72 work on it and i am giving level 3 improve Ui and also fix responsiveness

**Comment by AyushSharma72** [comment]
> @AyushSharma72 work on it and i am giving level 3 improve Ui and also fix responsiveness

Ok !
