### ISSUE TITLE
the contact us page is blank 

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#145]
the contact us page is not visisble 
![image](https://github.com/user-attachments/assets/8ce023a0-3483-467c-8fd6-22b96242723a)

please assign this issue to me @Yashgabani845

**Comment by Ashutoshdas-dev** [comment]
@Yashgabani845 i would like to solve this issue assigned it to me under the hacktoberfest labels

**Comment by AyushSharma72** [comment]
> @Yashgabani845 i would like to solve this issue assigned it to me under the hacktoberfest label

please raise you own issue

**Comment by Yashgabani845** [comment]
@AyushSharma72  it is resolved some link error was there
