### ISSUE TITLE
[Bug]  Follow us anchor tag not present.

### ISSUE THREAD

**Issue by Abhishek2634** [Yashgabani845/hiring-portal#15]
**Describe the bug**
when click on social icon nothing happens

**To Reproduce**
click on social icons nothing will happen

**Expected behavior**
when click, it should redirect to the social sites of owner.

**Screenshots**
<img width="293" alt="Screenshot 2024-10-02 at 2 42 19 PM" src="https://github.com/user-attachments/assets/03e3abe8-0ec2-4ac5-a1dd-f510bf5fbde7">

**Comment by Yashgabani845** [comment]
@Abhishek2634  this issue is already assigned ot someone kindly work on other issues and also work on issues which i already asssigned to you then make other issues
