### ISSUE TITLE
[Bug] I would like to add a loader 

### ISSUE THREAD

**Issue by c4dr-me** [Yashgabani845/hiring-portal#153]
**Describe the bug**
currently it shows loading..instead of that I would like to implement a better loader animation

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tanishq-singh-2407** [comment]
can I work on this?

**Comment by c4dr-me** [comment]
> can I work on this?

I realised that I was having network issues. loader is there
