### ISSUE TITLE
[Feature] Edit Profile Option

### ISSUE THREAD

**Issue by inkerton** [Yashgabani845/hiring-portal#154]
**Is your feature request related to a problem? Please describe.**
I recently created a new profile and added some languages. But they are being displayed under skills.
![image](https://github.com/user-attachments/assets/981316e7-50cc-49f2-8aab-8ae286141fe8)

**Describe the solution you'd like**
I want to add an edit option to each section so the user may edit their skills , languages, education details , Past Jobs details.
![image](https://github.com/user-attachments/assets/c6aff7a9-2b42-4e4d-b569-8b9263329b3a)

**Comment by Yashgabani845** [comment]
@inkerton work on it
