### ISSUE TITLE
[Bug] On Duplicate Values It shows Failed

### ISSUE THREAD

**Issue by inkerton** [Yashgabani845/hiring-portal#155]
**Describe the bug**
I tried to login using admin@gmail.com but I was unable to login as It showed an Error toast.

**To Reproduce**
1. Go to 'SignUp'
2. SignUp using admin@gmail.com
3. See error

**Expected behavior**
It should say that the user already Exists if it finds a duplicate value trying to signUp.

**Screenshots**
![image](https://github.com/user-attachments/assets/f04efb56-ab20-4f98-8e1f-20ade2edc8db)

**Comment by inkerton** [comment]
@Yashgabani845 Please assign it to me.

**Comment by Yashgabani845** [comment]
@inkerton it is reserved for admin if you have any alternaive for admin then tell it  otherwise show error that it has been taken

**Comment by inkerton** [comment]
If you are thinking of deploying the project you will need google auth and all else You cannot have admin@gmail.com as your admin details I would suggest add another role as 'Admin' or 'JobSeeker' or 'Employer'. Based on which you can differentiate . for now you can have a check if email = process.env.ADMIN_EMAIL. then assign role admin else by default jobseeker and if the user signs in via employee portal them employer.

It will make things more easy in the future also If you wish to add distinguished features for employers and job seeker.
@Yashgabani845

**Comment by inkerton** [comment]
On duplicate emails maybe give a forgot password option so the user can relogin again.

**Comment by inkerton** [comment]
It might be a person who is trying to signup again .

**Comment by Yashgabani845** [comment]
@inkerton it should not be done on signup handle this error and show message that user is already exist
(we do not have to assume that the person is owner of that particualer e mail id )
forget password may harm the account security

**Comment by Yashgabani845** [comment]
@inkerton if you need more info ask me or if you feel it can not be implemented then i can close this issue 
give me update

**Comment by inkerton** [comment]
I have thought of It I can make an API to check whether the email exists and if yes then We can show toast notifications . Their is no toast notification in the whole project if successfully loggedin or any error while logging in also their is nothing stated as to which values are compulsor and which are not if user leaves a cmpusory value empty it fails It should say to the user that Education cannot be empty of something . I can add toast notifications if You find this idea feasible.

For success

**Comment by inkerton** [comment]
![image](https://github.com/user-attachments/assets/72d069e4-e68c-4699-8b4e-7d9854a66de1)


for warning 
![image](https://github.com/user-attachments/assets/aba46af4-3613-4bb7-8fd9-f2794210e0b0)

for error 
![image](https://github.com/user-attachments/assets/f9b3192f-4151-42f6-826f-85c32d902ec6)

**Comment by inkerton** [comment]
I closed it by mistake let me know If you need notifications alarms or checks.

**Comment by Yashgabani845** [comment]
@inkerton notification is ok
