### ISSUE TITLE
[Feature] Logo design for Hirehub

### ISSUE THREAD

**Issue by Yashgabani845** [Yashgabani845/hiring-portal#16]
Design Professional Logo for hirehub and replace with current logo.png in src folder 
also make corrosponding favicon and put it in index.html

**Comment by slavomirStucka** [comment]
Hi i would like to design logo for Hirehub. Can i work on it?

**Comment by meghanakn473** [comment]
HEY @Yashgabani845  please assign me this issue, i want to work on it.

**Comment by Yashgabani845** [comment]
@meghanakn473 start working on it 
but i clarify Best logo will be accepted since you both want to work on same issue

**Comment by slavomirStucka** [comment]
I designed new logo, now it looks like this. 
![Snímka obrazovky 2024-10-03 113118](https://github.com/user-attachments/assets/e8649e27-e8ce-4b01-8822-3d929cbf2435)

**Comment by Yashgabani845** [comment]
@slavomirStucka good work 
@meghanakn473 any update from your side?

**Comment by meghanakn473** [comment]
> @slavomirStucka good work 
> @meghanakn473 any update from your side?

Yah im working on I'll share it within 8

**Comment by meghanakn473** [comment]
hey @Yashgabani845 i have actually updated my logo and related code link in the fork file....but im not able run the file and take the screenshot for proof...what do i do?

**Comment by meghanakn473** [comment]
![android-chrome-512x512](https://github.com/user-attachments/assets/53b7eb46-aa61-4e8d-a8ae-8bc1b0a78652)
@Yashgabani845  please check and review

**Comment by Yashgabani845** [comment]
i think @slavomirStucka has better one
@meghanakn473 this logo is good but it is not matching theme and size of requred space
@slavomirStucka  
you can make the PR

**Comment by Yashgabani845** [comment]
@slavomirStucka in logo make image of the logo smaller same as text in logo or slighlty larger then make PR for it
