### ISSUE TITLE
[Feature] Add hover effect on card and button.

### ISSUE THREAD

**Issue by Himanshu-kumar025** [Yashgabani845/hiring-portal#165]
**Is your feature request related to a problem? Please describe.**
the card has not any hover effect because of that user experience is not that good

**Describe the solution you'd like**
I like to add hover effect on the card and button.

Please assign me under GSSOC'24 and Hacktofest'24 .
thank you.
![hirehub](https://github.com/user-attachments/assets/dc234e89-17a7-47d1-951a-6db5b16501e5)

**Comment by sameer-soni** [comment]
@Yashgabani845 this issue hasn't been solved yet, can i get assigned? I'll complete this quickly

**Comment by Yashgabani845** [comment]
@sameer-soni  it is done by someone else still there is no update so i am closing it
