### ISSUE TITLE
UI/UX improvements and missing functionality in the login page

### ISSUE THREAD

**Issue by sps234** [Yashgabani845/hiring-portal#166]
login page some issues:

1. The "Remember Me" checkbox is placed between the "Sign In" button and the "Don't have an account? Sign Up" link, which creates a visually inconsistent layout and could confuse users.
2. The "Welcome to HireHub" text does not redirect to the main page, which may lead to frustration when users expect it to be clickable and navigate to the homepage.
3. There is no "Show Password" feature available, which makes it difficult for users typing lengthy passwords, leading to potential inconvenience and errors during input.

Solution:
1. Moving the "Remember Me" checkbox above the "Sign In" button for a more cleaner alignment.
2. Making the "Welcome to HireHub" text clickable and redirect it to the homepage or the main page of the application.
3. Adding a "Show Password" option next to the password field to allow users to view the password while typing, especially useful when entering long or complex passwords.

![Screenshot_16-10-2024_12818_main--hirehub07 netlify app](https://github.com/user-attachments/assets/216c0ea4-d1ec-4f9d-ae29-ad2a66fe9c12)

"Please assign this issue to me so that I can work on it."

**Comment by Yashgabani845** [comment]
@sps234 take care about responsiveness 
and share video in PR
