### ISSUE TITLE
Responsiveness of login page

### ISSUE THREAD

**Issue by krishpathak** [Yashgabani845/hiring-portal#168]
**Describe the bug**
Login page is not responsive.

**To Reproduce**
Fix the responsiveness of login page

**Expected behavior**
![image](https://github.com/user-attachments/assets/f0e5fef1-8b6e-4080-b232-50280b05bf54)

**Screenshots**
![image](https://github.com/user-attachments/assets/16ee2306-7a42-480c-a02c-2bd4ba4a8730)

**Comment by krishpathak** [comment]
@Yashgabani845 review this and assign me task.

**Comment by Yashgabani845** [comment]
@krishpathak it is responsive in local code prefer that rather than old deployed one
