### ISSUE TITLE
CSS improvement

### ISSUE THREAD

**Issue by Yashgabani845** [Yashgabani845/hiring-portal#17]
**Is your feature request related to a problem? Please describe.**
### improve CSS of jobview page 
make it proffestional do not chnage any details which is showing just chnage the layout 

### Related files
src/components/job.jsx
src/css/job.css

### Best design will be accepted
**give before and after view**

**Additional context**
![Screenshot 2024-10-02 154036](https://github.com/user-attachments/assets/0c4fb726-15e2-4633-8c61-5cf9ebe1497c)

**Comment by Sawan-Kushwah** [comment]
Will you assign me this #17 i want to work on this issue

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah  go ahead

**Comment by Yashgabani845** [comment]
@rohan-mate-28  start working on it and share working video in PR

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/2b9812cf-c65e-40ff-ba64-9eedcb50c7e6)
Is this looking good or should i do some changes?

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/27dddc2a-7bde-484b-af6e-07f23fe2e62b)
done is there any changes required?

**Comment by Sawan-Kushwah** [comment]
Should I separate recommend job by border-left ?

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah  yes and chnage and improve on each recommanded job

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/4cde5ec2-34f6-4d07-be40-ee96ee6cdad1)
See it Now okay ?

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah  done make the PR and share video of the page in PR
