### ISSUE TITLE
[Feature] Signup errors not acknowledged to user

### ISSUE THREAD

**Issue by Akshithsaai** [Yashgabani845/hiring-portal#179]
**Is your feature request related to a problem? Please describe.**
When I am trying to signup I may have Missed some fields. There are some required fields and due to that users are not able to register.

**Describe the solution you'd like**
I would like to add toast to these errors to notify the required changes to the users. 

![image](https://github.com/user-attachments/assets/4327c9e1-09bc-4c33-9807-9ed9bd015413)

@Yashgabani845 Currently I would like to work on the issue. I can also work on any other feature/bugs. Please assign me.

**Comment by shaharsh624** [comment]
/assign

Please assign me this issue

**Comment by Akshithsaai** [comment]
@Yashgabani845 Someone else rectified this error I think. Can You check and assign me level 2 or 3 issue.

**Comment by Akshithsaai** [comment]
@Yashgabani845 Please Check and let me know so that i could work on it .
