### ISSUE TITLE
[Bug] Navigation Buttons not working in mobile view

### ISSUE THREAD

**Issue by Akshithsaai** [Yashgabani845/hiring-portal#182]
**Describe the bug**
In a mobile view, Navigation buttons are not working and properly redirected. 

**To Reproduce**
1. Open console window (ctrl + shift + I )
2. click on the responsive button 
3. change it to mobile view 
4. try to navigate to jobs or about  us page.

**Expected behavior**
On clicking the icon , we should be navigated to the page. 

**Screenshots**

![image](https://github.com/user-attachments/assets/4c0b0552-8880-4cd8-b5a2-37701f229f61)

@Yashgabani845 I would like to work on this issue.

**Comment by mokshith-moksh** [comment]
can you assign me this issue

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by Akshithsaai** [comment]
@karandevhub please don't spam here.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.
