### ISSUE TITLE
[Bug] Content Misalignment

### ISSUE THREAD

**Issue by Bhum-ika** [Yashgabani845/hiring-portal#189]
**Describe the bug**
text and button are In left

**Expected behavior**
text and button should be in center

**Screenshots**
![image](https://github.com/user-attachments/assets/cf1cb673-61cb-4a00-8521-6b8dee6e0cba)

**Additional context**
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by Yashgabani845** [comment]
@Bhum-ika it is done check latest code by cloning repo
