### ISSUE TITLE
[Bug] Improve backend code

### ISSUE THREAD

**Issue by kritvisharma** [Yashgabani845/hiring-portal#19]
**Describe the bug**
Implementing routers, controllers and models in the backend code. Makes the code more structured and modular.

**Comment by Yashgabani845** [comment]
@kritvisharma 
go ahead !, but make changes sesitively and make sure all features are working correctly 
after making required changes test all parts and share working video in PR 
this is good issue , start work on it 
Thank you!
make sure ⭐star the repo

**Comment by harish08102004** [comment]
Hey @Yashgabani845 if this is not resolved may be I can work with it.
