### ISSUE TITLE
[Bug] Footer links not working 

### ISSUE THREAD

**Issue by Bhum-ika** [Yashgabani845/hiring-portal#191]
**Describe the bug**
On clicking on a particular link, footer navigates to home only

**Expected behavior**
It should navigate

**Additional context**
Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.

**Comment by DinukaUdawela** [comment]
can you assign me for this task

**Comment by Yashgabani845** [comment]
@Bhum-ika it is done check local latest code
