### ISSUE TITLE
UI improvement in About us Section

### ISSUE THREAD

**Issue by Bhum-ika** [Yashgabani845/hiring-portal#192]
The UI of about Us Page is very basic ,it should be appealing and attractive making users to read and know about the website. 
 I will work on this issue ,Kindly assign this issue to me under hactoberfest, gssoc-ext and relevant tags.
 
 
![image](https://github.com/user-attachments/assets/f04859f5-0ee3-4d25-8e52-d2ec931853a5)

**Comment by Yashgabani845** [comment]
@Bhum-ika it is done checkout local code
