### ISSUE TITLE
[Feature] Add sign up page

### ISSUE THREAD

**Issue by Prizag** [Yashgabani845/hiring-portal#196]
**Is your feature request related to a problem? Please describe.**
there is no signup page designed

**Describe the solution you'd like**
For new users there should be a sign up page to create their account . As of now there is no sign up page. Please assign me this task so iI can work on making this website and its user interaction better.

**Additional context**
![Screenshot 2024-10-19 145219](https://github.com/user-attachments/assets/0576c82b-ddea-48c6-b8ff-0aae5a59203e)

**Comment by Jashwanth-rit** [comment]
@Prizag signup page already exists.

![Screenshot 2024-10-19 171021](https://github.com/user-attachments/assets/4c329407-40b7-4a42-98ab-0f9e75e42353)

**Comment by Suvendu-UI** [comment]
pls assign me this issue

**Comment by mrhat05** [comment]
can you assign me for this?

**Comment by Yashgabani845** [comment]
@mrhat05 it is done
