### ISSUE TITLE
[Bug]: get job list according to feild not working.

### ISSUE THREAD

**Issue by Jashwanth-rit** [Yashgabani845/hiring-portal#197]
**Describe the bug**
as we go job section , we select a feild which we want , as we select it is not working.

**To Reproduce**
1. Go to job-page
2. Click on feild selection , 
3. select .

![Screenshot 2024-10-19 172121](https://github.com/user-attachments/assets/68e46581-9991-4144-a9ce-6b875f0c65b4)

**Comment by Yashgabani845** [comment]
@Jashwanth-rit you are watching old deployed code watch lastest code by cloning repo it is done
