### ISSUE TITLE
[Feature]: adding Faqs Page , so that Users get the answers for most common question

### ISSUE THREAD

**Issue by Jashwanth-rit** [Yashgabani845/hiring-portal#199]
Purpose of an FAQs Page:

- Reduce customer queries: Answers common questions to minimize repeated inquiries.
- Improve user experience: Helps users quickly find relevant information.
- Build trust: Clarifies policies, processes, or product features.
- SEO Benefits: Drives organic traffic by including relevant keywords.
![Screenshot 2024-10-19 172855](https://github.com/user-attachments/assets/730100ec-c172-41d4-8552-cec8e1e0088a)

**Comment by Yashgabani845** [comment]
@Jashwanth-rit it is done
