### ISSUE TITLE
Optimizing Homepage Design for 14-Inch Laptop Screens

### ISSUE THREAD

**Issue by c2gup** [Yashgabani845/hiring-portal#2]
@Yashgabani845 

I hope you’re doing well! I’m interested in working on the issue.

The homepage currently appears too wide when viewed on a 14-inch laptop screen, which impacts its visual appeal. The goal is to refine the design to make it look clean, balanced, and aesthetically pleasing on this screen size.

I am sharing an image with you which create problem **see he bottom of the image**
![Uploading Screenshot (182).png…]()

1. Adjust the width of the homepage to ensure that it is fully responsive, particularly on a 14-inch laptop screen.
2. Ensure that all elements on the homepage are well-proportioned and aligned properly.

Thanks!
Anupam Gupta

**Comment by Yashgabani845** [comment]
go ahead 
and make sure Responsive-ness should be maintained 
after making changes make PR and also share video/screenshot of homepage 
Thank you !😍
make sure star ⭐the repo

**Comment by Yashgabani845** [comment]
@c2gup  what is update?

**Comment by c2gup** [comment]
> @c2gup what is update?

Actually, I was busy with a hackathon, but I will complete it by 12 PM today. I'll update you once it's done. 
Thanks for asking

**Comment by Yashgabani845** [comment]
@c2gup  don't worry take your time

**Comment by harish08102004** [comment]
Hey @Yashgabani845 is this already closed ?

**Comment by Yashgabani845** [comment]
@harish08102004 no you can work on it

**Comment by STSonyThomas** [comment]
Hey since this hasn't been resolved already I can resolve this is an hours time.
Could you assign me to it?

**Comment by harish08102004** [comment]
Hey please go on I'm not working on this.

**Comment by Sourabh782** [comment]
@Yashgabani845 is this issue open? i would like to work on it

**Comment by Yashgabani845** [comment]
the prohram is done still no work update on first issue of proram what an irony😂
btw closing it
