### ISSUE TITLE
[Feature] Implement Job Post Form Page in Hiring Portal

### ISSUE THREAD

**Issue by IkkiOcean** [Yashgabani845/hiring-portal#222]
**Is your feature request related to a problem? Please describe.**  
Currently, there is no dedicated page for employers to post job openings, making it challenging for them to contribute new listings. This lack of functionality can lead to missed opportunities for attracting potential candidates and hinder the overall efficiency of the hiring process.

**Describe the solution you'd like**  
I would like to implement a Job Post Form page that allows employers to easily create and submit job postings. The form should include fields for job title, job description, location, employment type (full-time, part-time, contract, etc.), salary range, and any other relevant information. 

**Additional context**  
- The form should have validation to ensure that all required fields are filled out correctly.
- A success message should be displayed after the job post is successfully created.

### Please refer to this design mockup for the desired layout and user experience.
<img width="1279" alt="Screenshot 2024-10-24 at 4 48 31 PM" src="https://github.com/user-attachments/assets/724bcac4-1fd6-4462-9942-95fb6efd2c61">

**Comment by Yashgabani845** [comment]
@IkkiOcean it is done you can improve existing page go to employer section you will find it
