### ISSUE TITLE
[Bug] : not working login and signup page,

### ISSUE THREAD

**Issue by Jashwanth-rit** [Yashgabani845/hiring-portal#223]
**Describe the bug**
The login and signup functionalities are currently not working as expected. Users are unable to log in or register, which disrupts access to the platform. This issue needs to be resolved promptly to restore essential authentication features.

**To Reproduce**

1. open home page 
2. clickon login on navbar 
3. try to feed data.

![Screenshot 2024-10-24 191404](https://github.com/user-attachments/assets/654e2ee3-18d7-4e4f-88a8-14996877cb54)

**Comment by VanshKhod9** [comment]
plz assign this to me
