### ISSUE TITLE
[Feat]: adding create blog page. 

### ISSUE THREAD

**Issue by Jashwanth-rit** [Yashgabani845/hiring-portal#224]
**Describe the solution you'd like**
Implement a new Create Blog page to allow users to write and publish blog posts. This feature will provide an interface where users can input the blog title, content, and other relevant metadata (like tags or categories) before publishing.

![Screenshot 2024-10-24 191552](https://github.com/user-attachments/assets/34de8689-da9c-4017-959a-1f7c1735cddc)

**Comment by Yashgabani845** [comment]
@Jashwanth-rit it is added
