### ISSUE TITLE
Job section cards are not looking good , as professional 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Yashgabani845/hiring-portal#23]
![image](https://github.com/user-attachments/assets/84f26052-6543-4fdf-9f57-8c4ff2f4443d)

Suggestion 
we can improve the design of cards to make it more professional 

to see it click on job on navbar

**Comment by Sawan-Kushwah** [comment]
Can i work on this ? will you assign me #23

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah go ahead and share working video after making chnages 
required component 
src/components/jobcard.jsx
jobcard.css

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/318e9470-2253-4608-9f9c-ae404a0a68a1)

Look at this  @Yashgabani845 
is it looking fine or should i do some changes ?

**Comment by Yashgabani845** [comment]
improvise the buttons and also make logo slightly smaller 
otherwise design is quite good👍

**Comment by Sawan-Kushwah** [comment]
should i improvise view job button ? 
i have make whole card clickable as user point of view it is good

**Comment by Yashgabani845** [comment]
it is nice idea make whole card clickable
and improve Other CSS of the page according

**Comment by Sawan-Kushwah** [comment]
done should i make PR now ?

**Comment by Yashgabani845** [comment]
make PR after doing these chnages 
1. chnage css of company name which is currentl green 
2. make logo smaller amd then make PR
