### ISSUE TITLE
[Feature] Candidate Dashboard

### ISSUE THREAD

**Issue by shubhagarwal1** [Yashgabani845/hiring-portal#231]
Create a personalized dashboard where candidates can view their application status, saved jobs, and interview schedules.

**Comment by Yashgabani845** [comment]
@shubhagarwal1  it is done you can  make changes in it

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 it is done you can make changes in it

sure please assign me this task

**Comment by Yashgabani845** [comment]
@shubhagarwal1 you can create new issue with specifying which chnages do you want to make based on that i will assighn it to you

**Comment by shubhagarwal1** [comment]
> @shubhagarwal1 you can tell with specifying which changes do you want to make based on that i will assighn it to you

enhacing it more, giving it look and feel like a dashoard, show stats and if any new thing you want ther to be added that also i can do

**Comment by Yashgabani845** [comment]
@shubhagarwal1 go ahead but it should look better than current and should follow theme
