### ISSUE TITLE
[Feature] : Create Blog Page

### ISSUE THREAD

**Issue by haseebzaki-07** [Yashgabani845/hiring-portal#238]
**Is your feature request related to a problem? Please describe.**
I want to create a page for allowing users to create blogs. If it is already there I want to fix this so that the page is displayed and the frontend works as intended

**Describe the solution you'd like**
I will make a page in the frontend part of the project and make a API call to the necessary blog backend to actually store the blog in the database. 

![Screenshot 2024-10-25 170219](https://github.com/user-attachments/assets/d0a42144-9e89-4baa-90c0-a633c6d34469)

**Comment by Yashgabani845** [comment]
@haseebzaki-07 page is there you just give the path in app .js and test it
