### ISSUE TITLE
[Bug]: Employer/Post Job Button not as intended

### ISSUE THREAD

**Issue by haseebzaki-07** [Yashgabani845/hiring-portal#239]
**Describe the bug**
Employer/Post Job button is not working as expected.

**To Reproduce**
1. Go to Appbar
2. Click on Employer/Post Job
3. Does nothing

**Expected behavior**
It should redirect to the page where the jobs can be posted or it should show some message to the user to login if intended for the purpose. I will implement toast notification/messages for the purpose if user/job poster is not logged in.

**Screenshots**
![Screenshot 2024-10-25 170808](https://github.com/user-attachments/assets/cfd164aa-38d0-4a13-8b8b-65d8836a36c6)

**Comment by Yashgabani845** [comment]
@haseebzaki-07 it is doing 
but is you click wihtout signin then it is desabled 
you have to make sure that if user is not signed in then give toast otherwise redierct to dashboard 
as it is doing currently

**Comment by haseebzaki-07** [comment]
sure @Yashgabani845
