### ISSUE TITLE
[Feature] Loading Animation in pages

### ISSUE THREAD

**Issue by Yashgabani845** [Yashgabani845/hiring-portal#24]
### Description
Add loading animation in required pages 
1.spinners
2.3 dot and text animation 
whichever looks good 

**Additional context**
share video or photo of working and make PR

**Comment by itsmeAYUSH** [comment]
I would like to work on loading animations adding spinners and make it more user-friendly. 
Could you please assign this issue to me under GSSOC'24 extd and Hacktoberfest?
Thanks!

**Comment by arduvey29** [comment]
@Yashgabani845 Please tag it as level 1 or 2 and assign it to me, I would love to contribute
