### ISSUE TITLE
[Bug] Spelling of Hacktoberfest wrong at the tags for the repository

### ISSUE THREAD

**Issue by STSonyThomas** [Yashgabani845/hiring-portal#255]
**Describe the bug**
The tag of Hacktoberfest tag is wrong for the repo

**To Reproduce**
2. Click on '...'
3. Scroll down to '...'

**Expected behavior**
Hactoberfest is missing a K it should be Hacktoberfest

**Screenshots**
![image](https://github.com/user-attachments/assets/7ee6cc27-99ee-4a85-9096-b34ed5c0e9fa)

**Additional context**

**Comment by harith-hacky03** [comment]
I am eager to work on it.Can you assign me please!

**Comment by Yashgabani845** [comment]
@STSonyThomas  it is done
