### ISSUE TITLE
Implement Logo Click Functionality to Navigate to Home Page

### ISSUE THREAD

**Issue by AnushkaChouhan25** [Yashgabani845/hiring-portal#260]
I propose adding functionality to the logo on the website so that when users click on it, they are redirected to the home page. This is a common user experience practice that enhances navigation and improves overall usability.

###Suggested Changes:

- Implement a click event on the logo element.
- Ensure the click redirects users to the home page (e.g., /home ).

**Comment by Ashutoshdas-dev** [comment]
@AnushkaChouhan25 assign it to me i will like to do it

**Comment by VijeshVS** [comment]
@AnushkaChouhan25 
Can i work on this issue pls

**Comment by AnushkaChouhan25** [comment]
@Yashgabani845 Can you assign

**Comment by Yashgabani845** [comment]
@AnushkaChouhan25 it is done
