### ISSUE TITLE
[Feature] : Forget Password 

### ISSUE THREAD

**Issue by haseebzaki-07** [Yashgabani845/hiring-portal#268]
**Is your feature request related to a problem? Please describe.**
users should be allowed to reset the password of their account in case they forget.

**Describe the solution you'd like**
A otp shall be sent to their mails so that after succesful verification the users can reset their passwords.

**Comment by Yashgabani845** [comment]
@haseebzaki-07 go aheas current forget password feature has some issue it is good issue to work on

**Comment by Sawan-Kushwah** [comment]
@Yashgabani845  can i work on this ?

**Comment by haseebzaki-07** [comment]
@Sawan-Kushwah me working on it!
