### ISSUE TITLE
Add Arrow to First Section and Resolve Alignment Issue in the Second Section

### ISSUE THREAD

**Issue by Abbas7120** [Yashgabani845/hiring-portal#27]
![image](https://github.com/user-attachments/assets/c2b90508-d3aa-4251-bc7e-80989c181845)

Issue Title:
Add Arrow to First Section and Resolve Alignment Issue in the Second Section

Issue Description:
The current design for the homepage requires a few visual adjustments. Specifically, we need to add an arrow icon to the first section under the job roles to guide users visually. Additionally, the second section ("Post Your Job Opening Today!") has alignment issues that need to be corrected to ensure a clean and consistent layout.

Provide me this issue assign with gssoc-ext label I can resolve it

**Comment by Yashgabani845** [comment]
@Abbas7120  go ahead but make sure it should not affect resposiveness of the component

**Comment by Abbas7120** [comment]
Ok!
