### ISSUE TITLE
[Feature] Add Sign In and Sign Up Buttons to Navigation Header

### ISSUE THREAD

**Issue by subodhkangale07** [Yashgabani845/hiring-portal#275]
**Is your feature request related to a problem? Please describe.**
Currently, there are no visible sign-in or sign-up buttons in the navigation header of the hiring portal. This makes it difficult for users to access authentication features and creates a poor user experience for both new and returning users who need to access their accounts.

**Describe the solution you'd like**
Add two prominent buttons to the navigation header:

- A "Sign In" button for returning users
- A "Sign Up" button for new users who need to create an account

The buttons should:

- Be clearly visible in the top navigation bar
- Follow the portal's existing design system
- Have appropriate hover/focus states for accessibility
- Link to their respective authentication forms/pages

**Additional context**
This is a fundamental feature for any user authentication system and will improve:

- User experience
- Accessibility to account features
- Clear pathways for new user registration
- Overall portal functionality

**Comment by Ashutoshdas-dev** [comment]
@Yashgabani845 i will like to work on it olease assign it to me

**Comment by subodhkangale07** [comment]
@Yashgabani845 please assign this issue to me , I like to contribute in this , issue is raised by me
