### ISSUE TITLE
fix the placement of the login form 

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#28]
**Describe the bug**
the login form right now is not properly visible and user needs to scroll to view full form but it also leaves some space on the top we can use  that space to place it correctly

**To Reproduce**
1. Go to 'navbar'
2. Click on 'login'

**Screenshots**
![image](https://github.com/user-attachments/assets/6849f682-59e5-4dd8-ac12-794e4eee6d37)

fixing this issue will make the user experience instantly better

**Comment by Yashgabani845** [comment]
@AyushSharma72  start work on it but after pulling latest code and share video or screenshot in PR

**Comment by AyushSharma72** [comment]
> @AyushSharma72 start work on it but after pulling latest code and share video or screenshot in PR

Ok
