### ISSUE TITLE
[Bug] Sign up page not opening

### ISSUE THREAD

**Issue by Mrunali01** [Yashgabani845/hiring-portal#284]
**Describe the bug**
Sign up page isn't opening

**Screenshots**

https://github.com/user-attachments/assets/c24b2ffe-d2db-402e-b491-3286f5d24a72

Please assign this issue to me @Yashgabani845 under the labels gssoc-extd and level

**Comment by Yashgabani845** [comment]
@Mrunali01 it is done check local version
