### ISSUE TITLE
[Bug] owner page is not responsive

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#287]
the owner page is not responsive 
![image](https://github.com/user-attachments/assets/d155284a-797c-4c87-86d6-9e08db117bdb)
![image](https://github.com/user-attachments/assets/bce1d0cb-8dca-40ce-9e7c-ba7f99a8c726)

please assign  this issue to me @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72 i am giving level3 make it fully responsive and add animation
