### ISSUE TITLE
add eye icon to password field on login page

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#29]
**Is your feature request related to a problem? Please describe.**
 when the user logins he should have an option to toggle and see the password

**Describe the solution you'd like**
 i want to add the eye icon on the login page password field

![Screenshot 2024-10-03 220035](https://github.com/user-attachments/assets/1dca68f9-a148-410a-80bb-862ff0ed151b)

please assign this issue to me @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72  go ahead
