### ISSUE TITLE
[Feature] : Subscribe to the newsletter

### ISSUE THREAD

**Issue by haseebzaki-07** [Yashgabani845/hiring-portal#293]
**Is your feature request related to a problem? Please describe.**
Users filling in their mail ids in the newsletter form should receive a confirmation mail on their valid mail ids.

**Describe the solution you'd like**
will create a API in the backend of the project and integrate it with the frontend for the purpose.

**Comment by Yashgabani845** [comment]
@haseebzaki-07 it is done
