### ISSUE TITLE
[Bug] Footer responsiveness

### ISSUE THREAD

**Issue by laxmanp090404** [Yashgabani845/hiring-portal#3]
**Describe the bug**  
As shown in the attached screenshot, the footer is **not visually appealing** when viewed on different screen sizes. The **responsiveness** of the footer is not as expected, leading to layout issues and poor user experience, especially on smaller devices.

**To Reproduce**  
1. Go to the page with the footer component.
2. Resize the browser window or open the page on a mobile/tablet device.
3. Scroll down to the footer section.
4. Observe the footer layout and appearance.

**Expected behavior**  
The footer should be responsive and maintain a visually appealing layout across different screen sizes, ensuring a clean and consistent user experience on both mobile and desktop devices.

**Screenshots**  
![image](https://github.com/user-attachments/assets/e652c58a-6b3b-4cb3-85c1-4d76a6fba351)

**Additional context**  
This issue seems to occur when the screen size is reduced to tablet or mobile dimensions. Some elements appear misaligned or stretched, leading to an unbalanced layout. The footer should gracefully adapt to smaller screens while maintaining its intended design and structure.

**Comment by samkitsamsukha** [comment]
Hi there, I can work on this bug fix by adding relevant tailwind classes, can you please assign this to me?

**Comment by laxmanp090404** [comment]
@Yashgabani845 Please assign me under the label of gssoc extd 2024 and hacktoberfest

**Comment by Yashgabani845** [comment]
@laxmanp090404  
go ahead 
share screenshots in PR in different view or add a video 
Thanks !
make sure you ⭐the repo.

**Comment by Yashgabani845** [comment]
@samkitsamsukha  kindly work on some other issues 
thank you

**Comment by laxmanp090404** [comment]
@Yashgabani845  sure sir . I will work on it and share the results.
