### ISSUE TITLE
 add back button to the login form page

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#30]
**Is your feature request related to a problem? Please describe.**
when the user visit the login page he do not have nay option to navigate  back to the home page if he do not want to login

**Describe the solution you'd like**
 I want to add  a back button on the login page to help user navigate to the home page .

please assign this issue to me @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72  can you please pull latest code currently this is issue is also solved added navbar for back to home

**Comment by AyushSharma72** [comment]
> @AyushSharma72 can you please pull latest code currently this is issue is also solved added navbar for back to home

Whenever people visit repository they view the deployed project not by pulling that's why duplicate issues are coming please update the deployed version of the project
