### ISSUE TITLE
when there is no jobs a blank page is shown 

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#315]
when there is no data from the backend in the jons page nothing is shown 

![image](https://github.com/user-attachments/assets/5e6138ab-6d55-4739-99ac-8a843cf3a6e1)

i will add animation of no data like this :
![image](https://github.com/user-attachments/assets/b4e2e072-8d17-499e-a1be-90d98a0a42aa)

please assign this issue to  me under label level2 @Yashgabani845

**Comment by veepanshu-kasana** [comment]
@Yashgabani845 I want to contribute to this project on this particular issue. Please assign it to me!

**Comment by Yashgabani845** [comment]
@AyushSharma72 blank page is not indicated there is no job it is indicated jobs are still not loaded so you have to put loader with this same image which you shown in ss with text loading jobs ...

**Comment by Yashgabani845** [comment]
@AyushSharma72 blank page is not indicated there is no job it is indicated jobs are still not loaded so you have to put loader with this same image which you shown in ss with text loading jobs ...

**Comment by AyushSharma72** [comment]
> @AyushSharma72 blank page is not indicated there is no job it is indicated jobs are still not loaded so you have to put loader with this same image which you shown in ss with text loading jobs ...

No no I have inspected the api response the api gave an empty array then the blank page is shown means there is no jobs data in database.also I will add loader when the jobs are still loading @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72  agreed 
but i like design of loading so put  loading naimation at both empty and loading with different messages
