### ISSUE TITLE
[Feature] Add Hover and Color to Social Icons

### ISSUE THREAD

**Issue by Shekhar-Raj** [Yashgabani845/hiring-portal#32]
<h2>I want to add a hover effect to the social icons, so whenever i hover to icon the size of icon increases and each icon change their color to basic</h2>

<h3>Example</h3>

https://github.com/user-attachments/assets/d1489202-a584-478e-aa69-e1f1de424391

**Comment by Yashgabani845** [comment]
@Shekhar-Raj  work on it
