### ISSUE TITLE
improve the blogs page 

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#328]
i want to fix the alignment and  add pagination in the blogs page 
![image](https://github.com/user-attachments/assets/eb637dd5-f174-4f02-8397-303b7f70b16e)
right now the page do not have pagination and blogs make a stack

please assign this issue to  me @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72 i am giving level 3 make UI and good css which justify level 3

**Comment by AyushSharma72** [comment]
> @AyushSharma72 i am giving level 3 make UI and good css which justify level 3

ok @Yashgabani845
