### ISSUE TITLE
[Bug] login bug 

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#345]
even if the user login the profile page show no data in the localstorage

i logged in :
![Screenshot 2024-11-08 212933](https://github.com/user-attachments/assets/4e28c9d0-bd1b-4fc2-a422-eb410a5e05c1)

no data in localstorage:
![image](https://github.com/user-attachments/assets/ffc753cf-509a-4b0e-b735-4338da15cfc9)

there is some issue in the login function please assign this issue to me @Yashgabani845

**Comment by Yashgabani845** [comment]
@AyushSharma72 i think it is because someone has added google login directly without dealing with localstorage is it make conflict you can remove it 
also for perfect login with google you can make new issue of level3

**Comment by AyushSharma72** [comment]
> @AyushSharma72 i think it is because someone has added google login directly without dealing with localstorage is it make conflict you can remove it also for perfect login with google you can make new issue of level3

Ok I am making it

**Comment by nikhilritgithub** [comment]
is this issue resolved.?

**Comment by AyushSharma72** [comment]
> is this issue resolved.?

Yes
