### ISSUE TITLE
[Feature] No signup page 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Yashgabani845/hiring-portal#35]
**Is your feature request related to a problem? Please describe.**
 There is no signup page 

**Describe the solution you'd like**

assign me this i can build up a sign up page 
just tell me which info should i take and tell me about additional requirement so i can give you as best as possible !? 

**Additional context**
![image](https://github.com/user-attachments/assets/8c71508f-10ce-45b7-a758-e3005201bc6a)
You can see this click on login > then don't have an account you see this

**Comment by slavomirStucka** [comment]
there is signup page and it looks like that. Maybe you can create new issue, in which signUp page will be responzive and i think that this signUp form need to improve CSS. I can make that, but please can You open new issue? I just need to make my issues, which is opened by someone else not me. Thanks :D 

This is on from mobile view and second one is from web view
![before responzive](https://github.com/user-attachments/assets/958e6bd6-d67b-4cf3-8ae4-2e63d27ae867)
![before](https://github.com/user-attachments/assets/cb645fec-a785-418e-a64c-ac4979f73912)

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah  there is a signup page prefer local project then deployed version 
deployment link is older-one there are some backend issue on which i am working on prefer local porject after forking it and pulling latest version  signup code is fine
