### ISSUE TITLE
[Feature]  Implementing a Custom Scrollbar for Enhanced User Experience

### ISSUE THREAD

**Issue by SrijaVuppala295** [Yashgabani845/hiring-portal#350]
Description:
Is your feature request related to a problem? Please describe.
Yes, the current scrollbar lacks customization and doesn't align with the overall design of the website. It appears generic and can disrupt the cohesive aesthetic, especially on pages with extensive content. The default scrollbar can also be difficult to spot for users, especially on minimalistic or dark-themed designs.

Describe the solution you'd like
I would like to implement a custom scrollbar that aligns with the website’s theme and enhances user interaction. The custom scrollbar should be sleek and visually appealing, with a consistent style that complements the overall design of the site. It should be easy to spot and use, providing a smoother scrolling experience, and adapting to both light and dark themes.

Additional context
For example, in dark mode, the scrollbar could have a subtle glowing effect, while in light mode, it could be a transparent or soft gradient. The goal is to ensure that the scrollbar feels intuitive, visually integrated into the theme, and enhances the overall user experience without feeling intrusive.

**Comment by Yashgabani845** [comment]
it is done
