### ISSUE TITLE
Non responsive sign up form on mobile view

### ISSUE THREAD

**Issue by husar** [Yashgabani845/hiring-portal#36]
Need to improve css, to make it responsive
![JPEG obrázok-4DAE-BCE2-F4-0](https://github.com/user-attachments/assets/0a4bdec7-f2f8-471f-b1e1-67f7a116c71c)
![IMG_F1A0A410FD2E-1](https://github.com/user-attachments/assets/ef100de4-d15f-4a18-9e25-1e939a921df2)

**Comment by slavomirStucka** [comment]
Maybe i can take this issue and start right now. @Yashgabani845 Can you assign to me this issue ?

**Comment by Yashgabani845** [comment]
@slavomirStucka start working on it

**Comment by slavomirStucka** [comment]
@Yashgabani845  what do you think ?

![after responzive](https://github.com/user-attachments/assets/af972cea-cbaf-450d-8931-393f00cec779)
![after](https://github.com/user-attachments/assets/d0eac268-99df-4c1a-9c2d-d1b2380ee321)

**Comment by Yashgabani845** [comment]
Quite good 
But make sure it should not affect navbar of signin page and home page otherwise it's good 
Good to go for PR

**Comment by slavomirStucka** [comment]
When i pull last updates there was a small bug on navbar with not flexing the logo, but i fixed it. It should be better right now.
Here is photos from two views. Navbar looks good. can i go for PR?

##WEBview
![image](https://github.com/user-attachments/assets/dc6d352e-93b6-4a67-965c-dc798b1f2063)
![image](https://github.com/user-attachments/assets/b1dde626-4caa-4470-b02e-29933c774e7c)
![image](https://github.com/user-attachments/assets/e7d6fb07-6b8d-4797-98ab-7f18be878af7)

##MOBILEview
![image](https://github.com/user-attachments/assets/92476c8c-7355-491b-bd58-256157a9967f)
![image](https://github.com/user-attachments/assets/8ec91e5e-31aa-4934-9106-3e2dac612ae3)
![image](https://github.com/user-attachments/assets/b2e2e04a-9b64-4471-9fb0-13a20429cc06)


Maybe next issue can fix signIn form, zou can see that there are too much space around the signIn box
