### ISSUE TITLE
Home page is not responsive to mobile view

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Yashgabani845/hiring-portal#38]
![Screen Shot 2024-10-04 at 09 56 34](https://github.com/user-attachments/assets/e037aff1-dc3c-4c4a-899a-b0a4f54bab35)
As you can see in image !!

**Comment by Sawan-Kushwah** [comment]
Can i work on this ?

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah start working on it make full page responsive all of the 5 components I will assign level 3 PR

**Comment by Sawan-Kushwah** [comment]
Level tag of issue ?

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah  I will assign it after you make a PR

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/61b99dcf-ea73-4b19-99e5-d6b84aa56d5f

See it if any changes required tell me ?

**Comment by Yashgabani845** [comment]
Very nice make PR
