### ISSUE TITLE
[Feature]Add Navbar to Login Page for Better Navigation

### ISSUE THREAD

**Issue by grasyPatel** [Yashgabani845/hiring-portal#4]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex: I'm always frustrated when [...]

**Describe the solution you'd like**
Currently, the login page lacks a navigation bar, which makes it difficult for users to access other sections of the website, particularly the home page. Adding a navbar would enhance the user experience by providing easy access to important links.

**Additional context**
Benefits:
Improved user experience through easy navigation.
Consistent design across the website.
Potentially reduce user frustration by allowing quick access to other pages.
Additional Notes:
This change would align with the overall goal of making the website user-friendly and accessible.

<img width="1245" alt="Screenshot 2024-10-02 at 12 52 36 AM" src="https://github.com/user-attachments/assets/584b490f-35c3-4aec-ad05-28c822381bbe">

**Comment by grasyPatel** [comment]
@Yashgabani845 , I would like to request assignment on this issue so I can proceed with the implementation.

**Comment by Yashgabani845** [comment]
go ahead , share screenshot of the page ans also make this page reponsive for all views 

Thank you!
make sure you ⭐ the repo.
