### ISSUE TITLE
hirehub signup page not responsive image not display properly on small devices layout shows extra spaces top and bottom

### ISSUE THREAD

**Issue by Sureshwebdeveloper** [Yashgabani845/hiring-portal#40]
small screen 
![image](https://github.com/user-attachments/assets/8b921590-c771-4819-aa68-1a4582036775)

hirehub signup page not responsive image not display properly small screen image shows very small 
big screens it shows properly but big screens need to center a login signup page

big screen extra spaces on top and bottom
![image](https://github.com/user-attachments/assets/1b0109ba-aae0-4bb2-8017-33ddce4abd33)

**Comment by Yashgabani845** [comment]
@Sureshwebdeveloper  already done  prefer local project
