### ISSUE TITLE
when ever i will click Don't have an account? Sign Up it open unknow page  after click back button not opening hirehub

### ISSUE THREAD

**Issue by Sureshwebdeveloper** [Yashgabani845/hiring-portal#41]
![image](https://github.com/user-attachments/assets/a81b8913-0a71-4262-aa35-0c3e341e5947)

 Don't have an account? Sign Up it open unknow page  need to fix that only it will navigate to signup page 
plese assign to me If you assign to me I will fix it and add a label the gssocext and hactoberfest badges and add a level as well

**Comment by Yashgabani845** [comment]
@Sureshwebdeveloper you are just looking at deployed version setup project locally it is already solved locally
