### ISSUE TITLE
loader missing Job page

### ISSUE THREAD

**Issue by Kartikey2011yadav** [Yashgabani845/hiring-portal#46]
A proper loader is missing for jog description page. after clicking on jab card there is a certain delay in loading of jab page which is normal, but there is no loading animation on screen there is just a small div on top left stating `loading`.
 I want to add a appropriate loading animation for this

**Comment by Yashgabani845** [comment]
@Kartikey2011yadav  start working on it

**Comment by Kartikey2011yadav** [comment]
hey there please assign a level to this work
