### ISSUE TITLE
The home page is not proper responsive

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#49]
the home page is not  responsive i want to make it responsive 

![Screenshot 2024-10-04 203521](https://github.com/user-attachments/assets/0369c5e0-6470-4629-aa1d-ee8a88fed0ae)

![Screenshot 2024-10-04 203529](https://github.com/user-attachments/assets/7215a968-3e30-40ce-9fb7-a7f7b4ed09ff)

please assign me this issue with tag **level 2**  **hacktoberfest and gssoc-ext**

**Comment by Yashgabani845** [comment]
@AyushSharma72 i am assigning this issue but make sure laptop view should look same as current 
i have assigned someone previously but he messes up, do it carefully and then share both view laptop and mobile in video in PR

**Comment by AyushSharma72** [comment]
> @AyushSharma72 i am assigning this issue but make sure laptop view should look same as current i have assigned someone previously but he messes up, do it carefully and then share both view laptop and mobile in video in PR

The laptop view is looking fine I will make mobile view responsive will share video and images

**Comment by Yashgabani845** [comment]
okay work on it

**Comment by Sawan-Kushwah** [comment]
@Yashgabani845 home page responsiveness has been done he mighty using deployed link

@AyushSharma72 instead of deployment link use localhost to get updated code
