### ISSUE TITLE
[Bug] Improve navbar

### ISSUE THREAD

**Issue by shivamy009** [Yashgabani845/hiring-portal#5]
make navbar sticky across all page and make navbar more attractive 

please assign me to work on this issue

**Comment by Yashgabani845** [comment]
@shivamy009 
Current navbar is quite good still i am assigning this issue to you 
share screenshots in PR 
it will be accepted based on new look

**Comment by Yashgabani845** [comment]
@shivamy009 any updates ?
or if you are facing any issues then tell me

**Comment by Yashgabani845** [comment]
@shivamy009 i am closing th issue there is no upadte from 2 weeks
