### ISSUE TITLE
the about page is not responsive

### ISSUE THREAD

**Issue by AyushSharma72** [Yashgabani845/hiring-portal#50]
the about page is not responsive

![image](https://github.com/user-attachments/assets/f8d3b832-58cd-49f4-9786-2a9b6676cae2)

i want to make the about page responsive
please assign me this issue

**Comment by Yashgabani845** [comment]
@AyushSharma72 go ahead

**Comment by AyushSharma72** [comment]
> @AyushSharma72 go ahead

Please add level

**Comment by Yashgabani845** [comment]
@AyushSharma72 i will add it after PR is made
