### ISSUE TITLE
Profile section improvement and check on signup page 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Yashgabani845/hiring-portal#51]
![Screenshot 2024-10-04 191845](https://github.com/user-attachments/assets/03754e6e-0884-4cfe-acd3-076f3b1257b4)

we can improve this profile section with good UI

and instead of telling user at last that name mail password required we can resist the user before he move to next page 

![image](https://github.com/user-attachments/assets/9891a072-9c82-42d6-82d3-3aff3b90f31b)

also the layout of login design is not in center and instead of prefill we can use place holder in form and no footer present 

assign me this issue i can do all this things

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah  work on it 
but make only required changes and do changes after pulling latest code for avoiding conflicts
and in profile page share both video/ss in PR

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/66f3af79-3556-46ad-8eec-5eb3a19053d2)
See this any improvement needed?

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/fe968491-d439-4cc1-baf4-80f3ac44aeac)
See this any improvement needed ?

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah  design structure is good but it is has muc colour issues the blue colour at each thing is descresing readblity use gray and other theme colours for it like previous page had

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/6cdf3a40-d7f1-4490-9364-dc9430849ffe)
@Yashgabani845 see now ? it is fine to you

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah make skilld tags light gray , titles feild blue and make other things black and white and blue theme

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/31c08b77-7ad7-4ee2-b99d-5bbfd89cc86f)
@Yashgabani845 done with the changes see it if any more improvement let me know

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah good to go for PR
