### ISSUE TITLE
Update of READEM file as it doesn't contain project admin information etc.

### ISSUE THREAD

**Issue by Aditi-008** [Yashgabani845/hiring-portal#53]
I would like to add a project admin information section which will give the user full information about the project owner and help incase of issues to contact them. Kindly assign it to me under the label gssoc-ext and hacktoberfest-accepted along with the level of the problem.
Thank you!

**Comment by Yashgabani845** [comment]
@Aditi-008 go ahead and if you need any info then you're free to ask

**Comment by Aditi-008** [comment]
Sir would you like me to tell what all infos of yours are you ok with to be
put up. Also if possible you can share any discord or other channel if you
have. Basic information like name,mail id and linkedin I am working on it.

**Comment by Aditi-008** [comment]
Sir kindly merge it and also add hacktoberfest label
