### ISSUE TITLE
update Twitter Symbol to X in footer section[Bug] Your Bug Title

### ISSUE THREAD

**Issue by Amanjayswal500** [Yashgabani845/hiring-portal#55]
I would like to propose a change to update the Twitter symbol to "X"  to reflect Twitter's recent rebranding. This change ensures consistency with the platform's new identity and avoids any potential confusion for users. please assign this issue to me

**To Reproduce**
1. Go to the Footer section
2. Click on Follow us
3. See error

**Expected behavior**
current logo show

**Screenshots**
![Screenshot 2024-10-05 015001](https://github.com/user-attachments/assets/afb05c29-43be-48a6-8dfd-42c297c7d8e1)

**Comment by Yashgabani845** [comment]
@Amanjayswal500 work on it

**Comment by Sawan-Kushwah** [comment]
Can I do it?
