### ISSUE TITLE
 structuring Server.js

### ISSUE THREAD

**Issue by Manvitha-Vema** [Yashgabani845/hiring-portal#57]
The current server.js file has become cluttered and difficult to manage as it contains a significant amount of code related to routing, middleware, and controller logic. To enhance the maintainability and readability of the code, I propose restructuring the application by separating concerns through the use of routers and controllers.

Could you please assign it to me?

**Comment by Yashgabani845** [comment]
@Manvitha-Vema go ahead

**Comment by Sawan-Kushwah** [comment]
@Yashgabani845 if he is not able to do then please assign me!

**Comment by Manvitha-Vema** [comment]
> @Manvitha-Vema go ahead
Sure,could you also add hacktoberfest label too
