### ISSUE TITLE
[Feature] Backend Login & Signup (Controllers & Routes) Using JWT Auth on MongoDB

### ISSUE THREAD

**Issue by ParasY1724** [Yashgabani845/hiring-portal#58]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex: I'm always frustrated when [...]
Creating a MVC Followed Backend Structure , with endpoints for login and Signup.

**Describe the solution you'd like**
Backend Endpoint Creation : Login & SignUp

**Additional context**

**Comment by Yashgabani845** [comment]
@ParasY1724  i didn't get what you want to say

**Comment by yours7himanshu** [comment]
I wanted to create this please assign me..I had an experience in making user authentication using MERN

**Comment by Yashgabani845** [comment]
@ParasY1724  it is already done check local version of code
