### ISSUE TITLE
[Feature] Show password for sign in screen

### ISSUE THREAD

**Issue by 17arindam** [Yashgabani845/hiring-portal#59]
**Is your feature request related to a problem? Please describe.**
Currently there is no show password button and user cant see there typed password

**Describe the solution you'd like**
i will provide a toggle by which user can toggle between show and hide password

**Additional context**
![image](https://github.com/user-attachments/assets/1b28146b-0ec9-4994-8846-fdbfb05f46cd)

**Comment by 17arindam** [comment]
@Yashgabani845 please assign me this issue

**Comment by Yashgabani845** [comment]
@17arindam it's already done check latest code locally
