### ISSUE TITLE
Missing User Authentication and Sign Up page Problem

### ISSUE THREAD

**Issue by yours7himanshu** [Yashgabani845/hiring-portal#64]
@gabani-yash 
1)There is no user authentication mechanism in place. Implementing JSON Web Token (JWT) authentication with MongoDB is necessary to allow secure user registration and login.

2)Sign Up Page is broken

How to solve - We need to implement JSON Web Token (JWT) authentication with MongoDB.

**Comment by ParasharDeb** [comment]
I was wondering if you can assign me this issue

**Comment by Sawan-Kushwah** [comment]
@Yashgabani845 Assign me I can do this

**Comment by Yashgabani845** [comment]
@yours7himanshu  check out server.js and signin endpoint it is alredy done
