### ISSUE TITLE
[Feature] Improve Login Page Responsiveness 

### ISSUE THREAD

**Issue by SurajSG23** [Yashgabani845/hiring-portal#66]
Hey, i noticed that your website's login page is not responsive ! 

![image](https://github.com/user-attachments/assets/51048333-e0ae-42dd-9f53-2781945d7a0b)

I would like to fix it under gssoc and hacktober fest.
Please do assign me this. THANK YOU

**Comment by Yashgabani845** [comment]
@SurajSG23 it is already done check out local code
