### ISSUE TITLE
Project directory is completely messy 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Yashgabani845/hiring-portal#68]
As you see in the project directory the images are not properly arrange whenever we open src section its get hard to understand the structure at the very first time!

![image](https://github.com/user-attachments/assets/674ca120-25dc-4069-9886-06b322f97ed2)

i can arrange them in better way so that will will easy to understand the code directory structure and also change the link accordingly so it will not affect the website view

Assign me this issue i want to work on this !

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah work on it and test each endoints and images  every thing shoiuld work same as current

**Comment by Sawan-Kushwah** [comment]
![image](https://github.com/user-attachments/assets/9e4b347f-7e42-4e0d-8c11-203d988a725a)
should i delete this temp folder as it contains some c++ file which is not relavant to our project ?

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah good to go for PR if all iamges are working fine
