### ISSUE TITLE
To create a scrolling design on your website

### ISSUE THREAD

**Issue by anish013326** [Yashgabani845/hiring-portal#69]
#### To create a scrolling design on your website
User Engagement: Scrolling designs often feature captivating visuals and content, keeping users engaged as they explore the page.

**Comment by Yashgabani845** [comment]
@anish013326  go ahead
but it should look apealing and professional as job portal

**Comment by Yashgabani845** [comment]
@anish013326 any updates?

**Comment by Akanshaku** [comment]
I would like to work on it please assign @Yashgabani845
