### ISSUE TITLE
Change twitter logo to X

### ISSUE THREAD

**Issue by sachan13harshit** [Yashgabani845/hiring-portal#7]
#
**Screenshots**
![image](https://github.com/user-attachments/assets/b739cdfa-1d68-43f5-a18c-973eaca1287f)

**Comment by sachan13harshit** [comment]
@Yashgabani845 please assign this issue to me

**Comment by Yashgabani845** [comment]
@sachan13harshit  go ahead and also chnage the hover effect to different colour in each logo 
like gredient in instra , corrosponding black in github , blue in linkedin

**Comment by sachan13harshit** [comment]
Please assign it under hacktoberfest also

**Comment by Yashgabani845** [comment]
@sachan13harshit  this is project is only part of gssoc extended
