### ISSUE TITLE
[Bug] Fix Text Alignment Issue in Job Posting Section

### ISSUE THREAD

**Issue by Saurabhchaudhary9799** [Yashgabani845/hiring-portal#70]
**Describe the bug**
The text in the "Post Your Job Opening Today!" section is not properly aligned with the accompanying image and button. This creates an unbalanced visual layout, making the section appear uneven. The spacing between the text, button, and image needs adjustment to ensure they are symmetrically aligned and visually appealing.

**To Reproduce**

1. Go to the page containing the "Post Your Job Opening Today!" section.
2. Scroll down to the section with the image and the text.
3. Observe the alignment of the text, image, and button.

**Expected behavior**

- The text, button, and image should be symmetrically aligned.
- The text should be centered in relation to the image on the left and the button below the text.
- Spacing should be adjusted to make the section visually balanced.
**Screenshots**
![Screenshot from 2024-10-06 10-15-16](https://github.com/user-attachments/assets/14003a98-8072-4b4b-84a2-f7701e8b9b3f)

**Additional context**

The unbalanced layout negatively impacts the user experience, making the section appear disjointed.
Ensure consistent padding and margin between the text, button, and image for a cleaner appearance.

**Comment by Saurabhchaudhary9799** [comment]
hey @Yashgabani845 , could you please assign this to me?

**Comment by Yashgabani845** [comment]
@Saurabhchaudhary9799  work on it
