### ISSUE TITLE
Adding Testimonial Section to Enhance User Trust and Engagement

### ISSUE THREAD

**Issue by IshaRawat7** [Yashgabani845/hiring-portal#71]
Hii, @Yashgabani845 .
We can add testimonial section .The addition of a testimonial section on  website will significantly enhance user trust and engagement. This section will allow users to share their positive experiences and feedback, which can serve as powerful social proof.
We can continue with something Like this:

![Screenshot 2024-10-06 124112](https://github.com/user-attachments/assets/f5c31087-35e9-4b24-a229-82d528d2c0ce)

I would like to contribute over this.

**Comment by Yashgabani845** [comment]
@IshaRawat7  work on it but make css such that it should match with theme of the project and also match with topic of job portal 
make  new component and put it in homepage.jsx

**Comment by IshaRawat7** [comment]
Thank you @Yashgabani . I will continue working upon it now .

**Comment by Yashgabani845** [comment]
@IshaRawat7 i will assign it after seeing PR and contribution work
