### ISSUE TITLE
Build a FAQ section 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [Yashgabani845/hiring-portal#73]
There is a link in footer of FAQ but there is no faq section i am ready to build that page 
assign me this

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah work on it

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/9d910b7f-9ebb-4848-9cde-05999c8ec25a

![image](https://github.com/user-attachments/assets/2ae6eac3-86b4-4317-abc7-0fc29cc196b1)
uses best codding practices so if you need to add more FAQS the you can directly insert data in it 

same i did for colors no hard coded color so whenever in future you want you change the color theam 

Can i make PR or you need improvement in this ?

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah put FAQs section in homepage inself and also give simple black or grsy colour not blue

**Comment by Sawan-Kushwah** [comment]
@Yashgabani845 Okay done! Can I PR now

**Comment by Yashgabani845** [comment]
@Sawan-Kushwah go for PR
