### ISSUE TITLE
Preventing scrolling to the X-direction 

### ISSUE THREAD

**Issue by swamimalode07** [Yashgabani845/hiring-portal#76]
**Describe the bug**
The website is scrollable horizontally , which should not happen

**To Reproduce**
1. Go to 'Landing page'
2. try scrolling to the right side

**Expected behavior**
The website should not scroll to the rigth direction on X-axis

**Screenshots**
![image](https://github.com/user-attachments/assets/3ca25e58-6eae-4173-aa60-c68c783ce3d9)
![image](https://github.com/user-attachments/assets/57fe4482-7e93-4e62-be41-3c1268b9f37f)

**Additional context**
The problem is because of improper placing of the page content ,Kindly assign me this under GSSoC-extd and Hactoberfest

**Comment by Yashgabani845** [comment]
@swamimalode07  i do not think this issue is still there you can check latest local version
