### ISSUE TITLE
[Feature] Add "Contact Us" Page

### ISSUE THREAD

**Issue by Someshog** [Yashgabani845/hiring-portal#78]
**Overview:**
I would like to propose the addition of a "Contact Us" page to this project. This page should be easily accessible through the navbar or the footer for better visibility and user engagement.

**Implementation Details:**
1) File Location: `./src/components/ContactUs.jsx`
2) Navbar and Footer Links: Ensure that the "Contact Us" link is included in both the navbar and the footer for easy accessibility.

**Additional context**

Include a link to the "Contact Us" page in the main navigation bar as well as in the Footer.

![image](https://github.com/user-attachments/assets/ea1e3a3a-ade5-4a37-a41b-c21c3744c164)
<img width="398" alt="image" src="https://github.com/user-attachments/assets/61883b7a-7a20-4595-b554-ab2da39bab55">

**Comment by Yashgabani845** [comment]
@Someshog work on it
