### ISSUE TITLE
Adding on Upward arrow for scrolling to the top Feature

### ISSUE THREAD

**Issue by Aditya-edith** [Yashgabani845/hiring-portal#80]
This feature is a must as after scrolling to the bottom we usually find it lethargic to scroll to the top  so i can work on that for the same case

So basically there will be an arrow and on clicking it we will just reach at the top of the webpage

![Screenshot 2024-10-06 215812](https://github.com/user-attachments/assets/4142c2f2-7972-45ea-bac4-8131d6902a42)

**Comment by Yashgabani845** [comment]
@Aditya-edith work on it

**Comment by sameer-soni** [comment]
@Aditya-edith are you still working on this issue? if not, I'm interested in working on this feature.

**Comment by Yashgabani845** [comment]
@sameer-soni this issue is already solved
