### ISSUE TITLE
[BUG] footer issues on clicking the different links it is redirecting to home page even the about one

### ISSUE THREAD

**Issue by Aditya-edith** [Yashgabani845/hiring-portal#81]
footer issues on clicking the different links it is redirecting to home page even the about one to maintain the consistency we can add consistent routing for that

Onclick the different sections we will just redirect to the corresponding page 

![Uploading Screenshot 2024-10-06 215812.png…]()

**Comment by Yashgabani845** [comment]
@Aditya-edith  there are many pages , sections which are building in please wait it will be updated very soon
