### ISSUE TITLE
[Feature] Back to top button in each page

### ISSUE THREAD

**Issue by prasoonk1204** [Yashgabani845/hiring-portal#82]
**Is your feature request related to a problem? Please describe.**
It's really frustrating to scroll through a website from bottom to top, specially in this case where the header is not stuck on top of the screen

**Describe the solution you'd like**
I would like to add a floating button which takes the user back to the top of the page which is really helpful in case of long websites.

_please assign it to me_

**Comment by Yashgabani845** [comment]
@prasoonk1204 do it
