### ISSUE TITLE
[Feature] Dark mode

### ISSUE THREAD

**Issue by prasoonk1204** [Yashgabani845/hiring-portal#83]
**Is your feature request related to a problem? Please describe.**
The website lacks a dark mode option, which can lead to eye strain for users, especially in low-light. 

**Describe the solution you'd like**
Adding dark mode will improve user comfort and accessibility by giving them a choice to choose according to their preferences. And as developers, we all love dark mode

_please assign this to me_

**Comment by Yashgabani845** [comment]
@prasoonk1204 work on it

**Comment by SumitSahu44** [comment]
Yes @Yashgabani845 but the person working or not we don't know because it take 2days or maybe it is possible in a single day

**Comment by prasoonk1204** [comment]
@SumitSahu44 you can work on this issue, @Yashgabani845 please assign this issue to him also, I am working on it, but getting lots of errors. I'll still try to do it until sumit finishes it.

**Comment by Yashgabani845** [comment]
@SumitSahu44  start working on it

**Comment by arduvey29** [comment]
@Yashgabani845 Please assign this task to me

**Comment by SumitSahu44** [comment]
hey @Yashgabani845 I'm working on it so please don't assign to other it waste both time ,
hey @arduvey29 please try to solve other issue if it's not solve by me i sure it assign t you

**Comment by Yashgabani845** [comment]
@SumitSahu44 do not worry @arduvey29 work on some other issue

**Comment by STSonyThomas** [comment]
Hey dark mode seems like a pretty easy solve could you assign me this? I can get this done in under 1.5 hours.

**Comment by Yashgabani845** [comment]
@STSonyThomas please give update about it it's been more than  two week

**Comment by STSonyThomas** [comment]
I am not the one to whom the issue has been assigned. I want the issue to be assigned to me.

**Comment by STSonyThomas** [comment]
Assign me

**Comment by Sourabh782** [comment]
hello @Yashgabani845, if this issue is free i wanted to work on it i see its open for about a month, i have implemented similar functionality before, so i am confident i can deliver promising results

**Comment by STSonyThomas** [comment]
Hey I'm already working on it and am about 80 percent done.

**Comment by Yashgabani845** [comment]
@STSonyThomas do not worry keep working

**Comment by Yashgabani845** [comment]
@STSonyThomas any update?
