### ISSUE TITLE
Regrading GSSoC.

### ISSUE THREAD

**Issue by smog-root** [Yashgabani845/hiring-portal#84]
You need to add a level label to the issues. There are 3 levels. #78 #73 #72 #71 # ....

And you need to add  hacktoberfest-accepted.

**Comment by Yashgabani845** [comment]
@smog-root i generally add labels when you PR is got merged

**Comment by smog-root** [comment]
Okay. Just add the right labels!

**Comment by smog-root** [comment]
Your repo has benn short listed for not using the right labels.

https://docs.google.com/spreadsheets/u/0/d/1HogIA94g8XQnY1J2nfjFneUyuedxxO5TYAcYcbTBLhE/htmlview?pli=1

**Comment by Yashgabani845** [comment]
@Yashgabani845 it is for hactober becuase my project is not fro hectoberfest
