### ISSUE TITLE
(Documentation) #Add Code of Conduct

### ISSUE THREAD

**Issue by KiranBaliga** [Yashgabani845/hiring-portal#85]
Hey 🥳! I see that repository is missing code of conduct. I would like to add a code of conduct developed from scratch for your project. Please let me know if it is okay to proceed. Please assign to me and add GSSoC24 Ext & level1 Labels.

**Comment by Yashgabani845** [comment]
@KiranBaliga work on it

**Comment by KiranBaliga** [comment]
@Yashgabani845 Please review the PR and action accordingly. 

Please add level1 and gssoc-ext to the linked PR as well.

Thank you!
