### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by Meetjain1** [Yashgabani845/hiring-portal#86]
Dear Project Admin @Yashgabani845 

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by Yashgabani845** [comment]
@Meetjain1 i don't think so there is any PR without label of level and gssoc 
I generally prefer level label after PR got merged because otherwise the label could mislead the contribution

**Comment by Meetjain1** [comment]
Okay @Yashgabani845

**Comment by Yashgabani845** [comment]
@Meetjain1 i have added hactoberfest topic and now accepting hactoberfest contributions

**Comment by Meetjain1** [comment]
> @Meetjain1 i have added hactoberfest topic and now accepting hactoberfest contributions

@Yashgabani845 if so then add "hacktoberfest-accepted" labels in all prs

**Comment by Yashgabani845** [comment]
@Meetjain1 okay
