### ISSUE TITLE
[Bug] Your Bug Title

### ISSUE THREAD

**Issue by 0vai5** [Yashgabani845/hiring-portal#94]
**Describe the bug**
The Responsiveness of the Application 

**To Reproduce**
1. Go to any page
2. See a horizontal scroll on small devices and some of the content is not properly shown 

**Expected behavior**
Every page should be displayed correctly and may be not getting a horizontal scroll on small devices

**Screenshots**
![image](https://github.com/user-attachments/assets/f3a9d44f-1bb9-4376-b25f-e9740fdf2c2d)
![image](https://github.com/user-attachments/assets/e95a0e8f-5527-48c0-9d9e-9bbbf1c487f8)

Please assign me this task and also label this as gssoc-ext

@Yashgabani845

**Comment by 0vai5** [comment]
Please assign this to me @Yashgabani845

**Comment by Yashgabani845** [comment]
@0vai5 check latest code in local code this is already solved
