### ISSUE TITLE
[Feature] Good Looking and website suited scroll bar

### ISSUE THREAD

**Issue by VinayLodhi1712** [Yashgabani845/hiring-portal#95]
**Is your feature request related to a problem? Please describe.**
No its actually feature.

**Describe the solution you'd like**
I want to create a smooth scrollbar for the website.

**Additional context**
![vertical scroll](https://github.com/user-attachments/assets/8b054f8a-77ac-4a64-8777-b378016a8bd1)

https://github.com/user-attachments/assets/c542c1c9-fd85-43db-aba5-9d10f16d7c17

**Comment by Yashgabani845** [comment]
@VinayLodhi1712 start working on it
