### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by Garvit1000** [Yashgabani845/hiring-portal#97]
**Describe the bug**
when i click on  part time jobs it should show only  part time jobs but  it is  showing  all  it same in  entery level  ,mid level and senior level 

**To Reproduce**
1. Go to 'jobs'
2. Click on 'full-time jobs'
3. Scroll down  and  see before and after

**Expected behavior**
 it should show jobs on the basis of filter

**Screenshots**
before
![Screenshot from 2024-10-08 09-29-16](https://github.com/user-attachments/assets/6e33c49c-3480-40db-8d21-a568c7f221b4)
after
![Screenshot from 2024-10-08 09-29-24](https://github.com/user-attachments/assets/e4c108ee-fc99-4add-a40b-3c6ba0e90d9e)

**Additional context**
@Yashgabani845  assign this issue to me

**Comment by Yashgabani845** [comment]
@Garvit1000 if you want start working on it understand the backend feilds of job model and put filter accordingly

**Comment by Garvit1000** [comment]
I have  added filters. But to check them  when I tried to post new job it shows  api error should I continue that in  this issue  or  open a new one ? I can fix  that also.

**Comment by Garvit1000** [comment]
added 
![Screenshot from 2024-10-10 19-50-26](https://github.com/user-attachments/assets/db1fc4f3-3db3-4f9c-a0ae-0a3c7154d184)
![Screenshot from 2024-10-10 19-50-11](https://github.com/user-attachments/assets/9d8efce4-65a5-4e2d-befa-78ffb47a1b91)
all filters are working  should i go for PR
@Yashgabani845

**Comment by geetanjalidubey9** [comment]
pls assign this to me

**Comment by Garvit1000** [comment]
Posted PR
